### ISSUE TITLE
[Bug]: i dont have the game anymore even tho i bought it

### ISSUE THREAD

**Issue by fuigoizasfbhjavgfozga** [CompilerErrorRBX/Aftermath#83]
### What happened?

well ever since the easter update the  game was free and i already had bought it but now when i try to play it says i have to buy it for 199 even tho i already bought it i was looking into getting this fixed my user is. Mehrabmo

**Comment by CompilerErrorRBX** [comment]
You'll need to find the purchase record and submit this to Roblox support, we don't have any control over any part of this.
